aurelia/documentation

English/get-started.md
Spanish/get-started.md

Just a small fix in Getting Started document... and to get familiar with GitHub pull requests :)

doc(get-started): modify class name in child router sample from Welcome to ChildRouter

---

Japanese/docs.md

The first sentence of line of 13 in Japanese docs was
ほとんどのプラットフォームでは、"main"やコード実行の開始点があります。
It is difficult to understand and it probably mistake.

doc(Japanese/docs.md) fix a translation mistake

---

Chinese/get_started.md
Japanese/get-started.md

updated the sample code for Chinese and Japanese versions.
got a dist/app.js not found error when use 'gulp watch' on the old version.

fix(get-started): update index.html

---

English/docs.md

This adds the updated information on how to use Aurelia with IE9, note that we are down to only one additional polyfill

fix(IE9): update docs for IE9 support

---

English/get-started.md

Added instructions for installing the skeleton project via Yeoman rather than downloading and unzipping it. The Yeoman generator "generator-aurelia" just grabs the newest version of the skeleton project from GitHub, so it is more or less equivalent.
Also, I recently made a mistake changing the instructions to "open" the index.html instead of "creating" it, since I missed that the user had earlier been instructed to delete the file ahead of time. I've corrected it back to "create", plus I moved the initial deletion instructions into a new paragraph and reworded them a bit to accommodate people who would rather examine the files first.

Added reference to Yeoman, corrected conflicting "open/create"

---

English/docs.md

change `<tamplate>` to `<template>`

doc(docs.md): fix typo

---

English/docs.md

This adds a small bit of documentation on how to reference a parent VM for later use

doc(parent-vm): add documentation for parent vm referencing

---

English/docs.md

This adds a section to the documentation describing a situation
where a user wants to use the simplified "view" attribute of the
compose element, and bind an object directly as the view model of
that view.

doc(compose-vm-binding): add documentation about compose vm binding

---

English/docs.md

Changed quotes (') to backticks (`) for say-hello custom element

Changes to say-hello custom element

---

English/docs.md

Trying to follow the documentation, I found the example doesn't work... ?
1. MutationObserver.js pulled in by the first script tag runs immediately and requires WeakMap, so that throws an exception
2. after running `jspm install github:polymer/mutationobservers` I can reach the package with `polymer/mutationobservers` - just using mutationobservers fails.
I don't know if this is due to a later version of jspm, I'm not doing anything crazy, just following the setup of the skeleton project.
I guess if I am correct this will need changing in the other languages.

Correct way of including polyfills

---

English/get-started.md

I don't know if `title` was intentionally left out to show that it's optional. But without `title` the item doesn't show up in the menu.

Without `title` item doesn't show in menu

---

English/docs.md

Changing
`replace-part"someName"``
which is missing the '=' sign and has an extra '`' char.
To
`replace-part="someName"`

Fixing replace-part typo

---

English/get-started.md

Change requested by @zewa666 here: https://github.com/aurelia/skeleton-navigation/pull/135#issuecomment-130190502
Note: Moved the mention about Bower below all the jspm text. I believe this eases readability.

Adding mention on how to authorize jspm without giving github password

---

English/get-started.md

The beta release of JSPM is now the stable release. As such, to install a compatible version of JSPM for working with Aurelia the"@beta" tag and instructional note is no longer needed.

docs(getting-started): Removing JSPM beta installation instruction

---

English/docs.md

SVG tags need special help when being manipulated by anything that uses the `<template>` tag - a brief example was added to show how to properly overcome this limitation. It's super easy to fix but is a huge time waster if you don't already know about it.

added example for `<template>` inside `<svg>` tags

---

English/docs.md

doc change javascript example to include computedFrom import:
adding where the compuetdFrom binding is located in the javascript example

adding where computedFrom property is located in javascript example

---

current/en-us/2. tutorials/2. creating-a-contact-manager.md

Removed redundant `row` class from the `first-name` form group to improve conciseness.
Closes issue [#363](https://github.com/aurelia/documentation/issues/363)

doc (create-a-contact-manager): Removed redundant class on form group

---

current/en-us/7. plugins/7. virtualization.md

Cleaned up some of the copied text from the plugin README which had a few typos and grammatical errors.

docs(virtualization): formatting and typos

---

current/en-us/5. templating/4. custom-elements.md

Submitting documentation on `@processContent` for review. The suggestion coined from [the discussion on discourse](https://discourse.aurelia.io/t/better-know-a-framework-18-what-processcontent-is-and-what-it-is-used-for/1785).
@EisenbergEffect @bigopon Hope the details provided is easy to understand. However, please feel free to suggest/make edits.

Adding documentation on `@processContent`

---

current/en-us/5. templating/4. custom-elements.md
current/en-us/7. plugins/3. validation.md
current/en-us/7. plugins/4. i18n.md
current/en-us/7. plugins/6. animation.md
current/en-us/7. plugins/7. virtualization.md
current/en-us/8. integration/1. polymer.md

Because self-closing is not supported in HTML5. A note is added in the document.
@EisenbergEffect this replaces aurelia/validation#505

chore: remove all self-closing on HTML snippets

---

current/en-us/9. testing/1. components.md

This describes a new feature of aurelia-testing introduced by https://github.com/aurelia/testing/pull/89

doc(testing): add section on ignoring dependencies

---

current/en-us/9. testing/1. components.md

Reverts aurelia/documentation#389

Revert "doc(testing): add section on ignoring dependencies"

---

current/en-us/7. plugins/3. validation.md

The documentation now indicates the correct way to import the Validation plugin with webpack that is using `PLATFORM.moduleName('aurelia-validation')` instead of `.plugin('aurelia-validation')`.
This commit closes the issue #522.

docs(current): change to PLATFORM.moduleName('aurelia-validation')

---

current/en-us/7. plugins/2. store.md

@zewa666 can you have a look? I remove the mention of rxjs-compat because the rxjs migration guide  covered that, but I have no idea how to use rxjs-compat even after reading the migration guide.
The guide mentioned `npm install rxjs@6 rxjs-compat@6 --save` but has no code to `import 'rxjs-compat';`. How does it work?

doc(store): remove outdated instruction for aurelia-cli

---

current/en-us/11. cli/4. cli-bundler/4. cook-book.md

instructions on how to load the frontend wrapper for TypeORM and how to configure paths to point to your server entity files

docs(cli): cookbook entry for TypeORM in frontend

---

current/en-us/3. fundamentals/1. app-configuration-and-startup.md

The documentation now indicates the correct code for manual bootstrapping of an aurelia application using Webpack.
* changed the import from `import {bootstrap} from 'aurelia-bootstrapper-webpack';` to `import {bootstrap} from 'aurelia-bootstrapper';`
* using `PLATFORM.moduleName('app')` as `.setRoot()` argument.
This commit closes the issue #417 .

docs(current): change to PLATFORM.moduleName('app') and to 'aurelia-bootstrapper'

---

current/en-us/5. templating/2. html-behaviors.md

See fundamentals/creating-components#the-component-lifecycle which contains a duplicate of this lifecycle.
Except fundamentals/creating-components#the-component-lifecycle info box is clear and concise.
This page's version should be the same as the extra information doesn't add anything and also waters down the information contained with too much detail.

Reword HTML Behavior Lifecycle info to be same as fundamentals/creating-components#the-component-lifecycle

---

current/en-us/5. templating/3. custom-attributes.md
current/en-us/7. plugins/2. store.md
current/en-us/7. plugins/4. i18n.md

I originally sent one through change VM to view-model.
view-model is used 37 times across documentation, while ViewModel is used 13 times.
Yet ViewModel is a better choice as that is what outside documentation refers to in `Model-View-ViewModel` and searching in the repository for view-model will not find code samples.
Unifying to ViewModel makes more sense.

Vm to viewmodel

---

current/en-us/5. templating/5. content-projection.md

I think is a cut-and-paste error from the example above for `named-slot`

Fix incorrect element name in composed visual tree for fallback-content.

---

current/en-us/5. templating/5. content-projection.md

Composed Visual Tree was wrong.
Add missing `.html` suffix to require for html-only custom element.

Fix mixed-slot example.

---

current/en-us/2. tutorials/2. creating-a-contact-manager.md

Typo in filename under Adding Pub/Sub Messaging section.
Filename changed from "message.ts" to "messages.ts".

Contact Manager - Minor typo in filename "messages.ts"

---

current/en-us/7. plugins/5. dialog.md

It was discovered by Wendee https://discourse.aurelia.io/t/aurelia-dialog-styling-the-dialog-documentation-not-working-for-me/2800/3

doc(dialog): useDefaultSettings should be useDefaults

---

current/en-us/3. fundamentals/5. cheat-sheet.md
current/en-us/5. templating/4. custom-elements.md

The specific documentation for  @children, @child, @useShadowDOM needs to
reference that @containerless doesn't work.
The note that it doesn't work is further down and very easy to miss.

fix(containerless): inline notes for where it does not work

---

current/en-us/7. plugins/3. validation.md

the desctription refers to non-existent .role property

Fix typo in validation plugin docs

---

current/en-us/7. plugins/5. dialog.md

@3cp explains the issue here https://github.com/aurelia/dialog/issues/387 and here on [discourse](https://discourse.aurelia.io/t/ie11-dialog-promise-undefined/3240/16)
> v2 switched to native dynamic import() statement to simplify the code. This is indeed a breaking change for IE11.

Add warning about v2.0 and IE11

---

current/en-us/2. tutorials/2. creating-a-contact-manager.md

When this tutorial was upgraded from bootstrap v3 to v4, the layout is not quite right.
1. the left contact list is only clickable on the text, not the whole item.
2. the form layout is incorrect, leaving right side a blank gap.
3. some font size is too big, might due to bootstrap changes.
The updated code can be reviewed lively at https://gist.dumber.app/?gist=da1297fe5662ce31911cf5cb2bdce960
Also updated router config to use pushState.

doc(contact-manager-tutorial): fix layout issue in bootstrap v4

---

current/en-us/2. tutorials/2. creating-a-contact-manager.md

This was overlooked when I update the view template to latest bootstrap v4. There is no more li tag, only anchor tag.

fix(contact-manager-tutorial): update description to match latest code example

---

current/en-us/7. plugins/4. i18n.md

Replaced deprecated i18next-xhr-backend with i18next-http-backend. https://github.com/aurelia/i18n/issues/357

doc(i18n): replace deprecated i18next-xhr-backend
