Spanish/get-started.md

Hi Rob. Here is the get-started.md doc.

doc(documentation/Spanish): translate get-started.md into es-ES

---

English/docs.md

lots of developers are asking what is the minimum version of IE that Aurelia works with, so it would be helpful to add a browsers compatibility clause to answer their question.

Added Browsers Compatibility clause

---

English/docs.md

As requested by @EisenbergEffect  - I got round to this on the weekend - hope it's ok :)

doc(docs): added pushState info to Routing section

---

English/get-started.md

Just a couple of small errors I noticed whilst following the getting started guide.

Corrected spelling error and grammar.

---

English/docs.md

Correct small typo

---

Spanish/docs.md

Update docs.md es-ES after pushState, I'll try to keep the documents up to date.

docs(documentation/Spanish): update docs.md es-ES after pushState

---

English/get-started.md

line 191: main stream should be one word: mainstream
line 377: comma between inject and metadata
line 432: pipling should be piping

doc(get-started): fix spelling and grammar in three locations

---

English/docs.md

hope this looks good this time!

Added ASP.NET MVC routing configuration

---

Spanish/docs.md

Hi Rob! How did you do this week? The translation is kept up to date.

docs(documentation/Spanish/docs.md): update translation to last changes

---

English/docs.md

Short description plus a sample of route filters.

doc(router): Document route filters

---

Spanish/docs.md

Translation updated to your last merge.

docs(Spanish/docs.md): 2015-02-17 translation up to date

---

English/docs.md

Corrected a small typo in the HTTP Client section.

doc(english docs): Minor typo correction

---

style-guide.md

This should help community when contributing and when referencing their own JavaScript styles to adopt.  This is the starting point of the style guide.

feature(style-guide): Add starting style guide for reference

---

English/docs.md

doc(english docs): Fix typo

---

Japanese/get-started.md

Hi, I translated get started document into Japanese. Doc.md translation isn't finished yet (I will continue to work on it) , so please merge this ahead.

doc(documentation/Japanese): translate get-started.md into ja-JP

---

English/docs.md

This adds some information how VMs can be reused by either forcing a VM reload or reevaluation of the VMs life-cylce

feat(example): Adds info about reusing VMs

---

Chinese/get_started.md

This add the Chinese version of the get started guide, the complete doc is still under working.

doc(documenttion/Chinese): translate get_started.md into zh-CN

---

Japanese/docs.md

Japanese translation of doc.md (latest).

doc(documentation/Japanese/doc.md) translate doc.md into ja-JP

---

English/docs.md

Adds additional information on how to create configurable plugins

feat(plugins): Info on plugin configuration

---

English/docs.md

I thought activate() would have an id parameter

<doc>(route-patterns): using 'property' instead of 'parameter'

---

English/docs.md

Seeing a lot of confusion around this in the gitter because folks typically aren't installing aurelia-templating.

chore(docs) import templating assets from aurelia-framework

---

English/get-started.md

There seems to be an issue with jspm and/or system.js on older versions of npm that results in the app not running. Add a note to the getting started document so other readers are prompted to update npm if the app doesn't run.

doc(get-started.md): add a reminder to update npm

---

English/get-started.md

Make it simpler to follow the getting started guide with the correct bootstrap style.

Updated app.js in the examples with require bootstrap

---

Japanese/docs.md
Japanese/get-started.md

catch it up to latest English doc (docs.md, get-started.md). some improvement on translations.

fix(docs): update Japanese translation to latest

---

Spanish/docs.md

docs spanish translation up to date (April, 16th, 2015).

doc(docs): update Spanish translation

---

English/get-started.md

The index.html file is already provided in skeleton project, so the documentation should reflect this. Here's my suggestion for updating the text.

Change from "creating" to "opening" index.html

---

Spanish/docs.md
Spanish/get-started.md

Update Spanish translation of get-started.md and docs.md up to April,
24, 2015

doc(Spanish): update translation

---

English/docs.md
Japanese/docs.md
Spanish/docs.md

See aurelia/binding#83 and aurelia/router#78.

update to new activationStrategy and bindingMode APIs

---

English/docs.md

Added documentation associated with this fix: https://github.com/aurelia/templating-resources/issues/50

doc(docs.md): add "x of count" repeat

---

English/docs.md
Spanish/docs.md
Spanish/get-started.md

The second commit of the three included has a wrong commentary: its a modification in the original English document.

docs(documentation/Spanish): update docs.md and get-started.md

---

English/get-started.md
Japanese/get-started.md
Spanish/get-started.md

Hi,
I found a minor typo in the example of TypeScript and fixed it.
We decided to use Aurelia. We support you.
Best,
Hirano Satoshi

fixed:  The type of http should be HttpClient.

---

English/docs.md

This adds initial documentation for template parts.

chore(docs): Add preliminary template part docs

---

Japanese/docs.md

Update Japanese translation to latest English/docs.md ( commit f7a80ae2251c7b6a83b95623bdbda390bc5844ef )

fix(docs.md): update translation to latest

---

English/get-started.md

Without the button, there is no way to display the menu in mobile layout.

Needs a button in order for menu to work

---

English/docs.md

Has been missing and requested

Add interceptors section

---

Portuguese-Brazil/get-started.md

Translation of Get-Started.md to pt-BR

doc(documentation/Portuguese-Brazil): add get-started.md in pt-br

---

Chinese/get_started.md
English/docs.md
English/get-started.md
German/get-started.md
Japanese/docs.md
Japanese/get-started.md
Spanish/docs.md
Spanish/get-started.md

Relates to aurelia/skeleton-navigation#120

docs(getting-started): remove type from link tags

---

English/docs.md

Typo with my-behavior

---

Portuguese-Brazil/get-started.md

Removing link tag and fixed grammar

doc: (documentation/Portuguese-Brazil) remove type from link tags 

---

Japanese/docs.md
Japanese/get-started.md

Update Japanese translation to latest commit Jul-27,  5e766b84124e5aacf6836d3a7e77ee1aec2c0858

fix(documentation/Japanese): update to latest

---

Japanese/get-started.md

update to: f1c332faff4316d94bd6efbb04353e4fd59d3452
It's breaking changes, so translate get-started first for Japanese newbie.

fix(get-started.md): update to latest get-started.md

---

English/docs.md

Matches the latest version of the API

chore(docs): update globalizeResources to globalResources

---

Indonesian/get-started.md

Hi, I translated the Get Started document into Indonesian.
Thanks.

doc(documentation/Indonesian): translated get-started.md into id-ID

---

English/get-started.md

"This callback with be invoked with a configuration object."
=>
"This callback will be invoked with a configuration object."

fix(get-started): fixes minor typo

---

current/en-us/7. plugins/6. animations.md

still need to polish the article,
follow the discussion [here](https://github.com/aurelia/documentation/issues/181#issuecomment-445117657)

added Animations: Basic

---

current/en-us/4. binding/1. basics.md

fixing $ rendering in code sample

---

current/en-us/7. plugins/7. virtualization.md

Adds in initial documentation for the UI Virtualization plugin.

doc(virtualization): initial docs

---

current/pt-br/1.visão geral/1.o-que-e-aurelia.md

I would like to help in the Portuguese translation, so I started translating the first part.

translate pt-br cpt 1-1

---

current/en-us/2. tutorials/2. creating-a-contact-manager.md

There is a typo so the example does not work.

Fix final version of app.html w/loading-indicator

---

current/en-us/3. fundamentals/5. cheat-sheet.md
current/en-us/5. templating/1. basics.md

aurelia/templating-resources#320
aurelia/templating-resources#364

Add docs for if without cache

---

current/en-us/5. templating/4. custom-elements.md

same as https://github.com/aurelia/documentation/issues/372

fix rendering of $ for custom-elements.md

---

current/en-us/11. cli/7. recipes.md

https://github.com/aurelia/cli/pull/1034#issuecomment-461190661

Added recipe to workaround readonly attribute set by TFS

---

current/en-us/7. plugins/3. validation.md

related to aurelia/validation#519

docs(validation): document new numeric validation rules

---

current/en-us/4. binding/8. value-converters.md

Fixed documentation bug https://github.com/aurelia/framework/issues/927

Update 8. value-converters.md

---

current/en-us/11. cli/1. basics.md
current/en-us/7. plugins/8.write-new-plugin.md

@EisenbergEffect this is for aurelia/cli#1075

docs(plugins): draft write-new-plugin

---

current/en-us/7. plugins/2. store.md

fixes the JS samples shown for the store plugin

docs(plugin): fix up js samples for store plugin

---

current/en-us/3. fundamentals/5. cheat-sheet.md
current/en-us/5. templating/4. custom-elements.md

Add example and add optional options param.
Related: https://github.com/aurelia/templating-resources/pull/368

doc(shadow-dom, custom-elements): Add example

---

current/en-us/7. plugins/4. i18n.md

additional notes about when potentially not to use TCustomAttribute approaches and prefer TValueConverter or TBindingBehaviors
related issue https://github.com/aurelia/i18n/issues/302

docs(i18n): add clarification about perf implications

---

current/en-us/6. routing/1. configuration.md

doc(router-view): add inherit-binding-context section

---

current/en-us/7. plugins/6. animation.md

Update 6. animation.md

---

current/en-us/6. routing/2. handling-links.md

Updated link to DefaultLinkHandler to point to updated typescript source.

Update links for DefaultLinkHandler

---

current/en-us/4. binding/1. basics.md

doc(binding-basics): fix a typo

---

current/en-us/7. plugins/2. store.md

Explanation and sample for the piped dispatch feature

docs(dispatch): piped dispatch explanation

---

current/en-us/7. plugins/4. i18n.md

docs(i18n): remove broken deep links

---

current/en-us/4. binding/12. binding-engine.md

I've answered question about binding engines for a few times, so I think it would be best if we could have a section dedicated to it.
Would be nice if @baerrach could help with this too ❤️ 
cc @EisenbergEffect 
Note: it's super crude 😬

doc(binding-engine): add basic doc for binding engine

---

current/en-us/7. plugins/3. validation.md

doc(validation): remove unneeded cli guide

---

current/en-us/9. testing/1. components.md

doc(testing/components): Fix code sample for custom component with a real view model

---

current/en-us/12. build-systems/docker/1. setup.md
current/en-us/12. build-systems/docker/README.md

In this PR, I am trying to add some documentation to indicate how it is possible to dockerize Aurelia application.
cc/ @EisenbergEffect

Add documentation for Docker builds

---

alpha/English/docs.md
alpha/Japanese/docs.md
alpha/Spanish/docs.md
current/drafts/durandal-to-aurelia.md
current/drafts/manual-webpack-configuration.md
current/en-us/11. cli/1. basics.md
current/en-us/11. cli/5. migrating.md
current/en-us/11. cli/6. updating.md
current/en-us/12. build-systems/2. jspm/2. bundling.md
current/en-us/2. tutorials/1. creating-a-todo-app.md
current/en-us/2. tutorials/2. creating-a-contact-manager.md
current/en-us/3. fundamentals/1. app-configuration-and-startup.md
current/en-us/7. plugins/3. validation.md
current/en-us/7. plugins/4. i18n.md
current/en-us/7. plugins/5. dialog.md
current/en-us/7. plugins/6. animation.md
current/en-us/7. plugins/7. virtualization.md
docs-v2/drafts/getting-started/cli.md
docs-v2/drafts/getting-started/preparing-your-machine.md
docs-v2/drafts/getting-started/webpack.md

Also cleaned up outdated npm commands and outdated au run commands.

Update TODO tutorial to use cli

---

current/en-us/10. ssr/1. introduction.md
current/en-us/7. plugins/6. animation.md

Relates to https://github.com/aurelia/animator-css/issues/70

doc(amination): enter/leave animation ending

---

current/en-us/7. plugins/3. validation.md

See aurelia-validation release 1.6.0

Document the defaultValidationTrigger config option

---

current/en-us/7. plugins/3. validation.md

Documentation for the changes made in https://github.com/aurelia/validation/pull/544/
@bigopon @EisenbergEffect This can be merged after the PR is merged and the new major version of aurelia-validation is released. Keeping things in pipeline :)

docs(validation): for PR 544

---

current/en-us/2. tutorials/1. creating-a-todo-app.md

Fixes broken link to 'App Configuration and Startup' page

doc(tutorial/Quick start): Fix broken link

---

current/en-us/2. tutorials/1. creating-a-todo-app.md

This PR is ment to fix all the TS warnings that pop up after copying the example code.

doc(tutorial/Quick start): Fix TS warnings in example code

---

current/en-us/7. plugins/5. dialog.md

Man.. we have this for such a long time..  https://github.com/aurelia/dialog/pull/338
I never knew.. Even though I participated in discussion 🤦‍♂️

fix(docs) mention NativeDialogRenderer

---

current/en-us/5. templating/1. basics.md

long overdue: https://github.com/aurelia/templating/issues/565

chore(doc) mention table template incompatibility

---

current/en-us/2. tutorials/1. creating-a-todo-app.md

fix: fix link again

---

current/en-us/7. plugins/4. i18n.md

i18next--backend -> i18next-xhr-backend

doc(i18n): typo
